"""add cover url to pdfs

Revision ID: 171df89ee8bd
Revises: 54732cca325d
Create Date: 2024-12-07 18:50:23.228542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '171df89ee8bd'
down_revision: Union[str, None] = '54732cca325d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust if needed ###
    op.add_column('pdfs', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust if needed ###
    op.drop_column('pdfs', 'cover_url')
    # ### end Alembic commands ###